apiVersion: v1
kind: Service
metadata:
  name: ingestion-manager
  labels:
    app: ingestion-manager
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    name: http
  - port: 7000
    protocol: TCP
    name: metrics
  selector:
    app: ingestion-manager
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ingestion-manager-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ingestion-manager
    spec:
      hostAliases:
      - ip: "192.168.1.91"
        hostnames:
          - "master.test.cloudera.daf.teamdigitale.it"
          - "master"
      - ip: "192.168.1.92"
        hostnames:
          - "slave1.test.cloudera.daf.teamdigitale.it"
          - "slave1"
      - ip: "192.168.1.112"
        hostnames:
          - "slave2.test.cloudera.daf.teamdigitale.it"
          - "slave2"
      - ip: "192.168.1.93"
        hostnames:
          - "edge1.test.cloudera.daf.teamdigitale.it"
          - "edge1"
      - ip: "192.168.1.85"
        hostnames:
          - "idm.test.daf.teamdigitale.it"
          - "idm"
      containers:
      - name: ingestion-manager
        image: ${IMAGE_URI}
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: "-server -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -Xmx2g -Xms2g -XX:MaxPermSize=1024m"
        ports:
        - name: client
          containerPort: 9000
        - name: metrics
          containerPort: 7000
        volumeMounts:
        - name: glusterfsvol
          mountPath: /opt/docker/conf/production.conf
          subPath: ingestion-manager/conf/production.conf
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/conf/logback.xml
          subPath: ingestion-manager/conf/logback.xml
          readOnly: true
        - name: krb5conf
          mountPath: /etc/krb5.conf
        - name: glusterfsvol
          mountPath: /etc/hadoop/conf
          subPath: etc/hadoop/conf
          readOnly: true
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
